/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MisComponentes.JCajaSeguridad;

import java.awt.Color;

import java.util.ArrayList;

/**
 *
 * @author alumno
 */
public class JCajaSeguridad extends javax.swing.JPanel {

    /**
     * Creates new form JCajaSeguridad
     */
    //PropiedadPublica
    private String ID_CajaSeguridad;
    private int num_id;

    //PropiedadPrivada
    private int pswd = 1111;
    private boolean bloqueado;
    private int contador = 1;

    //GETTERS Y SETTERS
    public String getID_CajaSeguridad() {
        return ID_CajaSeguridad;
    }

    public void setID_CajaSeguridad(String ID_CajaSeguridad) {
        this.ID_CajaSeguridad = ID_CajaSeguridad;

    }

    public int getNum_id() {
        return num_id;
    }

    public void setNum_id(int num_id) {
        this.num_id = num_id;
    }

    //METODOS
    public void Abrir() {

    }

    public void Abrir(int pswd) {

    }

    public void Cerrar() {
        jLabelNum.setText("LOCKED");

    }

    public void Desbloquear() {
        jLabelNum.setForeground(Color.GREEN);
        jLabelNum.setText(String.valueOf(pswd));

        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButtonOC.setEnabled(true);
        jButtonSel.setEnabled(true);
        jButtonPswd.setEnabled(true);
    }

    public JCajaSeguridad(String id) {
        this.ID_CajaSeguridad = id;
        initComponents();
        jPanelVerde.setBackground(Color.GREEN);

    }

    //LISTENER
    private ArrayList<JCajaSeguridadListener> listeners = new ArrayList();

    public void addMetronomoListener(JCajaSeguridadListener listener) {
        listeners.add(listener);
    }

    public void removeMetronomoListener(JCajaSeguridadListener listener) {
        listeners.remove(listener);
    }

    //LANZADORES
    protected void lanzaJCajaSeguridadAbrir() {
        JCajaSeguridadEvent ev = new JCajaSeguridadEvent(this);
        for (int i = 0; i < listeners.size(); ++i) {
            JCajaSeguridadListener aux = (JCajaSeguridadListener) listeners.get(i);
            aux.JCajaSeguridadAbrir(ev);
        }
    }

    protected void lanzaJCajaSeguridadCerrar() {
        JCajaSeguridadEvent ev = new JCajaSeguridadEvent(this);
        for (int i = 0; i < listeners.size(); ++i) {
            JCajaSeguridadListener aux = (JCajaSeguridadListener) listeners.get(i);
            aux.JCajaSeguridadCerrar(ev);
        }
    }

    protected void lanzaJCajaSeguridadSeleccionar() {
        JCajaSeguridadEvent ev = new JCajaSeguridadEvent(this);
        for (int i = 0; i < listeners.size(); ++i) {
            JCajaSeguridadListener aux = (JCajaSeguridadListener) listeners.get(i);
            aux.JCajaSeguridadSeleccionar(ev);
        }
    }

    protected void lanzaJCajaSeguridadBloquear() {
        JCajaSeguridadEvent ev = new JCajaSeguridadEvent(this);
        for (int i = 0; i < listeners.size(); ++i) {
            JCajaSeguridadListener aux = (JCajaSeguridadListener) listeners.get(i);
            aux.JCajaSeguridadBloquear(ev);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jLabelNum = new javax.swing.JLabel();
        jButtonPswd = new javax.swing.JButton();
        jButtonSel = new javax.swing.JButton();
        jButtonOC = new javax.swing.JButton();
        jPanelVerde = new javax.swing.JPanel();
        jPanelRojo = new javax.swing.JPanel();

        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, 36));

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 11, -1, 36));

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 11, 38, 36));

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 11, -1, 36));

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 11, -1, 36));

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 11, -1, 36));

        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelID.setText("ID_CajaSeguridad_Num");
        jLabelID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 58, 257, -1));

        jLabelNum.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNum.setForeground(new java.awt.Color(0, 255, 0));
        jLabelNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelNum.setOpaque(true);
        add(jLabelNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 96, 147, 42));

        jButtonPswd.setText("Contraseña");
        jButtonPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPswdActionPerformed(evt);
            }
        });
        add(jButtonPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 58, -1, -1));

        jButtonSel.setText("Seleccionar");
        jButtonSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelActionPerformed(evt);
            }
        });
        add(jButtonSel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jButtonOC.setText("Cerrar");
        jButtonOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOCActionPerformed(evt);
            }
        });
        add(jButtonOC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 89, -1));

        jPanelVerde.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelVerdeLayout = new javax.swing.GroupLayout(jPanelVerde);
        jPanelVerde.setLayout(jPanelVerdeLayout);
        jPanelVerdeLayout.setHorizontalGroup(
            jPanelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        jPanelVerdeLayout.setVerticalGroup(
            jPanelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanelVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 96, -1, 47));

        jPanelRojo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelRojoLayout = new javax.swing.GroupLayout(jPanelRojo);
        jPanelRojo.setLayout(jPanelRojoLayout);
        jPanelRojoLayout.setHorizontalGroup(
            jPanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanelRojoLayout.setVerticalGroup(
            jPanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        add(jPanelRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        comprobar();
        jLabelNum.setForeground(Color.green);
        String aux = jLabelNum.getText();
        EscribirNum(1, aux);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        comprobar();
        jLabelNum.setForeground(Color.green);
        String aux = jLabelNum.getText();
        EscribirNum(2, aux);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        comprobar();
        jLabelNum.setForeground(Color.green);
        String aux = jLabelNum.getText();
        EscribirNum(3, aux);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        comprobar();
        jLabelNum.setForeground(Color.green);
        String aux = jLabelNum.getText();
        EscribirNum(4, aux);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        comprobar();
        jLabelNum.setForeground(Color.green);
        String aux = jLabelNum.getText();
        EscribirNum(5, aux);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        comprobar();
        jLabelNum.setForeground(Color.green);
        String aux = jLabelNum.getText();
        EscribirNum(6, aux);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPswdActionPerformed
        // TODO add your handling code here:
        if (jLabelNum.getText().length() == 4) {
            if (bloqueado == false) {

                pswd = (Integer.parseInt(jLabelNum.getText()));
                jLabelNum.setText("");
                jPanelVerde.setBackground(Color.WHITE);
                jPanelRojo.setBackground(Color.red);
                jButtonOC.setText("Abrir");
                bloqueado = true;
            }
        }


    }//GEN-LAST:event_jButtonPswdActionPerformed

    private void jButtonOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOCActionPerformed
        // TODO add your handling code here:
        if (jButtonOC.getText() == "Abrir") {
            if (contador < 4) {
                int numero = 0;
                try {
                    numero = Integer.parseInt(jLabelNum.getText());
                } catch (Exception e) {

                }
                if (pswd == numero) {
                    jButtonOC.setText("Cerrar");
                    jPanelVerde.setBackground(Color.green);
                    jPanelRojo.setBackground(Color.white);
                    lanzaJCajaSeguridadAbrir();
                    contador = 1;
                    jLabelNum.setText("");
                    bloqueado = false;

                } else {
                    jLabelNum.setForeground(Color.red);
                    jLabelNum.setText("error");
                    contador++;

                }
            } else {
                jLabelNum.setForeground(Color.red);
                jLabelNum.setText("locked");

                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                jButton6.setEnabled(false);
                jButtonOC.setEnabled(false);
                jButtonSel.setEnabled(false);
                jButtonPswd.setEnabled(false);
                lanzaJCajaSeguridadBloquear();

            }

        } else if (jButtonOC.getText() == "Cerrar") {
            jButtonOC.setText("Abrir");
            lanzaJCajaSeguridadCerrar();
            jPanelVerde.setBackground(Color.WHITE);
            jPanelRojo.setBackground(Color.red);
            jButtonOC.setText("Abrir");
            bloqueado = true;
        }
    }//GEN-LAST:event_jButtonOCActionPerformed

    private void jButtonSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelActionPerformed
        // TODO add your handling code here:

        lanzaJCajaSeguridadSeleccionar();
    }//GEN-LAST:event_jButtonSelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonOC;
    private javax.swing.JButton jButtonPswd;
    private javax.swing.JButton jButtonSel;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JPanel jPanelRojo;
    private javax.swing.JPanel jPanelVerde;
    // End of variables declaration//GEN-END:variables

    private void EscribirNum(int n, String aux) {

        if (jLabelNum.getText().length() < 4) {
            jLabelNum.setText(aux + String.valueOf(n));
        }

    }

    private void comprobar() {
        if (jLabelNum.getText() == "error") {
            jLabelNum.setText("");
        }
    }
}
